name: 'blender'
save:
    folder: './results'
arch:
    max_epochs: 50
checkpoint:
    save_top_k: 5
    monitor: 'abs_rel_pp_gt'
    monitor_index: 0
model:
    checkpoint_path: './weights/pretrain/indoor_scannet.ckpt'
    name: 'SupModelMF'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthPoseNet'
        version: 'it12-h-out'
    loss: 
        automask_loss: True
        photometric_reduce_op: 'min'
    params:
        crop: ''
        min_depth: 0.01
        max_depth: 100.0
datasets:
    augmentation:
        image_shape: (320, 320)
    train:
        batch_size: 6
        dataset: ['Blender']
        path: ['/data/Datasets/blender/blender-duodenum-5-211126']
        split: ['']
        depth_type: ['velodyne']
        repeat: [1]
        forward_context: 1
        back_context: 1
        num_workers: 1
    validation:
        dataset: ['Blender']
        path: ['./dataset']
        split: ['']
        depth_type: ['velodyne']
        forward_context: 1
        back_context: 0
    test:
        dataset: ['EndoSLAM']
        path: ['/data/Datasets/EndoSLAM/UnityCam/Stomach/Frames']
        split: ['']
        depth_type: ['']
        forward_context: 1
        back_context: 1
